### ISSUE TITLE
XML support doesn't work with proxies

### ISSUE THREAD

**Issue by PeterTheF0x** [eclipse/wildwebdeveloper#192]
Hello,

After upgrading eclipse to 2019-06, I get an error for all my pom.xml files when I open them.

org.eclipse.lsp4E.diagnostic (1 item)
  Error while downloading 'http://maven.apache.org/xsd/maven-4.0.0.xsd'.

I have check all parameters about proxy and everything looks fin, also I was experiencing this problem in the past with the version 2019-03.

This error is annoying as it put lot of "false" red cross errors on all of my projects.

NOTE: I have post this issue to lsp4e bugzilla (https://bugs.eclipse.org/bugs/show_bug.cgi?id=549267) but they say the error is coming from your project.

Best regards,
Pierre Huttin

**Comment by mickaelistria** [comment]
Thanks.
Do I get it right that you're using a proxy?
I think the issue is that proxy settings in Eclipse IDE are not forwarded to the XML language server.
#121 might be able to solve that (no guarantee).
@angelozerr Are there specific settings to pass to the XML Language Server to deal with proxies? Or should we just pass the usual Java system properties at startup?

**Comment by PeterTheF0x** [comment]
Yes I'm using a proxy, I have try to set it in "Windows > Preferences > General > Network Connections "and I have also try by setting the proxy settings in eclipse.ini file using : -Dhttp.proxy... parameters. Nothing seems to work.

**Comment by angelozerr** [comment]
@PeterTheF0x WWD consumes the XML Language Server. Your error comes from this project https://github.com/angelozerr/lsp4xml

The downloading of XML Schema/DTD is done the first time to download the XML Schema/DTD from declared with URL in your XML and store it in a local cache. There are some issues with https like
https://github.com/angelozerr/lsp4xml/issues/419 but maven.xsd doesn't use HTTPS. I suspect a problem with proxy like @mickaelistria said.

LSP4XML can be configured to support proxy. See https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/XMLServerLauncher.java#L34

> @angelozerr Are there specific settings to pass to the XML Language Server to deal with proxies? Or should we just pass the usual Java system properties at startup?

Yes XML Language Server supports proxy. Please see 
https://github.com/redhat-developer/vscode-xml/wiki/Preferences#server-vm-arguments

**Comment by kingoleg** [comment]
Hi,

Is there any work around for it?

**Comment by mickaelistria** [comment]
Not yet. If you're interested in submitting a patch for this (setting `http.proxyUser/http.proxyPassword` in command line at https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/XMLLanguageServer.java#L47 according to existing system properties or other Eclipse proxy settings), I'd be glad to review and merge it.

**Comment by mickaelistria** [comment]
This should be fixed in next snapshot build and next release.

**Comment by shankarwww** [comment]
Hi all,

I think this issue is back again in eclipse-jee-2020-03-R-incubation-win32-x86_64.

I am getting the below error after using this new version of eclipse:
Error while downloading 'http://java.sun.com/xml/ns/javaee/ejb-jar_3_0.xsd' to C:
 \Users\sk\.lsp4xml\cache\http\java.sun.com\xml\ns\javaee\ejb-jar_3_0.xsd.

**Comment by mickaelistria** [comment]
Please open a new ticket with more details about how to reproduce, you proxy settings and so on.

**Comment by amoyano** [comment]
> Hi,
> 
> Is there any work around for it?

Open it with Admin role
