### ISSUE TITLE
Support for TypeScript 3.9

### ISSUE THREAD

**Issue by 4javier** [eclipse/wildwebdeveloper#508]
I just upgraded my Angular project to v10.
This version adopts TypeScript 3.9 and leverages the new Solution-Type configurations file. 
https://angular.io/guide/migration-solution-style-tsconfig

Now, when I open my updated project in STS with WWD, I got an error on every class definition, telling me that
>Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.

The proposed option is already set inside `tsconfig.base.json`, as Angular 10 default, but I think the lack of TS3.9 support make WWD ignores it.

**Comment by mickaelistria** [comment]
This might have been fixed recently with https://github.com/eclipse/wildwebdeveloper/commit/dbd5111dbd895a662adf92d47d275d7f0d9c7d76
Can you please try to upgrade to latest snapshot build from https://download.eclipse.org/wildwebdeveloper/snapshots/ and report whether this works better for you?

**Comment by 4javier** [comment]
It seems to work again with org.eclipse.wildwebdeveloper_0.5.10.202008281220 snapshot.
There's still an error validating tsconfig.json, but that's due to the choice of Angular devs to put some comment inside that, making it non compliant with json spec. Then I think it's not a bug.
Thanks a lot for your quick solution.
Cheers.

**Comment by mickaelistria** [comment]
Thanks for testing!
