### ISSUE TITLE
editing html tags automatically adds attributes to the closing html tag (which should never happen)

### ISSUE THREAD

**Issue by r6squeegee** [eclipse/wildwebdeveloper#814]
this has been happening to me for a while now, but specifically right now I'm on eclipse build 20220310-1457 
with "Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools	0.10.13.202204031849"

I'm on a blank line in an html file, and i type the following : 
`<div></div>`
     

What I really want is 
`<div class="foo"></div>`
though so I use the arrow keys to move back behind to the letter "v" and I press "space" and start typing the word "class". 

The editor starts adding that to the closing tag, i.e. I end up with
`<div class="foo"></div class="foo">`
 then I hit ctrl-z to undo and the editor completely screws up. i.e. it seems to randomly delete some characters and makes a complete mess of the surrounding lines of code. Basically I have to close the file with out saving and re-open it to get back to a sane state.

**Comment by nitind** [comment]
I'm also seeing this in the updated Maven POM Editor if I just wait for a few moments with the cursor at the end of the start tag's name.

**Comment by angelozerr** [comment]
> I'm also seeing this in the updated Maven POM Editor if I just wait for a few moments with the cursor at the end of the start tag's name.

It is a problem with linked editing range. For XML (LemMinx it should be fixed with https://github.com/eclipse/lemminx/pull/1188) Once WWD will use last version of lemMinx, this error should disapear.

For HTML, it requires that vscode html language servcer written in TypeScript do the same fix than XML.

**Comment by vrubezhny** [comment]
@r6squeegee Could you please try updating LSP4E from a latest snapshot - http://download.eclipse.org/lsp4e/snapshots/ - this should allow the linked editing to happen only for the element names, not the following attributes.

**Comment by mickaelistria** [comment]
Could not reproduce with latest snapshots. Please reopen with details to reproduce if issue persists on your end.

**Comment by mickaelistria** [comment]
Fix is https://github.com/eclipse/lsp4e/commit/a427c473db97c5f4d9920795025f0f3a20c10278
