### ISSUE TITLE
Please do not include JustJ JREs in your update site

### ISSUE THREAD

**Issue by merks** [eclipse/wildwebdeveloper#938]
Please **do not** include JustJ JREs in your update site:

https://download.eclipse.org/wildwebdeveloper/snapshots/plugins/

People with that site available will generally end up updating to whatever JRE you are providing there:
```
[2022-09-14 10:10:58] Downloading org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64
[2022-09-14 10:10:58] Fetching org.eclipse.justj.openjdk.hotspot.jre.full_18.0.1.v20220515-1614.jar from https://download.eclipse.org/wildwebdeveloper/releases/0.15.0/features/ (21.46kB)
[2022-09-14 10:10:58] Fetching org.eclipse.justj.openjdk.hotspot.jre.full_18.0.1.v20220515-1614.jar from https://download.eclipse.org/wildwebdeveloper/releases/0.15.0/plugins/ (19.84kB)
[2022-09-14 10:10:58] Fetching org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_18.0.1.v20220515-1614.jar from https://download.eclipse.org/wildwebdeveloper/releases/0.15.0/plugins/ (112.34MB)
[2022-09-14 10:10:59] Fetching org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_18.0.1.v20220515-1614.jar from https://download.eclipse.org/wildwebdeveloper/releases/0.15.0/plugins/
```

```
[2022-11-02 14:15:53] Fetching org.eclipse.justj.openjdk.hotspot.jre.full_19.0.0.v20221005-1658.jar from https://download.eclipse.org/wildwebdeveloper/snapshots/plugins/ (19,81kB)
[2022-11-02 14:15:53] Fetching org.eclipse.wildwebdeveloper.xml_1.0.0.202210262109.jar from https://download.eclipse.org/wildwebdeveloper/snapshots/plugins/ (8,48MB)
[2022-11-02 14:15:53] Fetching org.eclipse.justj.openjdk.hotspot.jre.full_19.0.0.v20221005-1658.jar from https://download.eclipse.org/wildwebdeveloper/snapshots/features/ (23,28kB)
[2022-11-02 14:15:53] Fetching org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_19.0.0.v20221005-1658.jar from https://download.eclipse.org/wildwebdeveloper/snapshots/plugins/ (116,67MB)
[2022-11-02 14:15:54] Fetching org.eclipse.wildwebdeveloper.xml_1.0.0.202210262109.jar from https://download.eclipse.org/wildwebdeveloper/snapshots/plugins/
[2022-11-02 14:15:54] Fetching org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_19.0.0.v20221005-1658.jar from https://download.eclipse.org/wildwebdeveloper/snapshots/plugins/
```

**Comment by mickaelistria** [comment]
Unfortunately, this is not easy: JustJ is included in the RCP product and every transitive dependency is included in a p2 repo when it's built from an RCP product.

**Comment by vrubezhny** [comment]
Now should be fixed with #1238

**Comment by sratz** [comment]
It's not really fixed.

#1238 removed the justj artifacts from the actual repo, however, simply the fact that the `category.xml` contains a `<repository-reference>` to JustJ still causes unwanted updates to justj itself.

1. Before
![image](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/assets/14908423/813bf58a-8936-4982-a0f1-2a8567e06fab)

2. Check for updates
![image](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/assets/14908423/43301271-7f1a-49e7-8936-7cbcba124ed2)

3. Press **Cancel** (!) and check update sites again:
![image](https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/assets/14908423/2f7d2d9f-8f33-4b16-8b50-67755aaa2f65)


This is all very unusual:
- WildWebDevelopers decides to filter our JustJ in the `category.xml` to control what to bundle
- Yet, for some reason this causes P2 to add a repository in the list of available update sites and initiates updates that are not desired. Is this really intended?

**Comment by sratz** [comment]
I have opened a follow-up ticket #1380 for this issue.
