### ISSUE TITLE
"Rename" sometimes fails

### ISSUE THREAD

**Issue by AndrewFerr** [eclipse/wildwebdeveloper#951]
Attempting to rename a token intermittently fails with an error dialog of "The Rename request is not valid at the given position".

What tends to help is to close & reopen an editor, and to always trigger the rename action via the right-click context menu instead of a keyboard shortcut.  But sometimes even this fails until the second or third try.

**Comment by akurtakov** [comment]
For clarity - can you tell what type of file with example you try to edit? E.g. rename in html and js may work but not in ts or rename of variable works but not of function.

**Comment by AndrewFerr** [comment]
It was in a Typescript file, for both a local variable & a class property.

The same happens with classes & class methods: a rename usually fails, but after retrying enough times, it may eventually succeed.

**Comment by mickaelistria** [comment]
Thanks for linking @AndrewFerr , I indeed suspect that https://github.com/eclipse/lsp4e/pull/298 should fix it; so there is nothing to be done on Wild Web Developer side. You may want to try installing latest snapshots of LSP4E to leverage @angelozerr 's fix.

**Comment by AndrewFerr** [comment]
Unfortunately this is still broken with WWD 1.0.1.202211171559 and LSP4E 0.15.0.202211181007.  Possibly related is https://github.com/eclipse/lsp4e/issues/309.

**Comment by AndrewFerr** [comment]
This is still an issue with WWD 1.0.2.202302250247 and LSP4E 0.20.0.v20230216-1815.  It's at the point where I can't get a "Rename" operation to succeed after repeated attempts.

Notably, "Find References" succeeds on tokens that "Rename" fails on.  (I've been trying them both on functions & local variables in a toy TS file.)

**Comment by mickaelistria** [comment]
@AndrewFerr Can you please re-update to latest snapshots? Many things were changed, mostly in LSP4E, that may have fixed this issue.

**Comment by AndrewFerr** [comment]
It still occurs, unfortunately. Rename attempts fail for both functions & variables, on both references & definitions.
Plugin versions installed:
- Wild Web Developer: 1.0.4.202303161605
- LSP4E: 0.16.1.202303171257

**Comment by vrubezhny** [comment]
@AndrewFerr  @Lucas3oo Are you referring to `Refactoring->Rename` in JavaScript or in TypeScript files?

**Comment by vrubezhny** [comment]
@Lucas3oo  Do you sea an error dialog like the following instead of the Rename Wizard for a TypeScript file?

![Screenshot from 2023-05-15 16-03-28](https://github.com/eclipse/wildwebdeveloper/assets/620781/9d7d6875-5511-4f5b-ade7-753bf68b6602)

**Comment by vrubezhny** [comment]
I have created #1209 in order to track the issue.

**Comment by Lucas3oo** [comment]
Yes that is the dialogue and error message I get.

Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools version: 1.0.5.202304192009
